### ISSUE TITLE
Installation Fails

### ISSUE THREAD

**Issue by phoward38** [prakhar1989/dive-in#6]
When attempting to install from either Docker Desktop or Docker Hub, an error message is thrown:
> Dive was not found. Click the button below to install Dive

However, clicking the button doesn't resolve the issue, nor does manually installing `dive` CLI. I'm using Docker Desktop `v4.15.0` on MacOS (M1) `v12.6.2`.

**Comment by krankkkk** [comment]
For anyone having this issue, clear out your local image cache and try again.
For me it was an issue with an image that has no tags, resulting in `App.tsx` line 48 failing exceptionally because `i.RepoTags` is null/undefined.


Also the plugin doesn't seem to use the local installation, but rather pulls the required docker image and uses that instead. 
So having `dive` installed it locally makes no difference for this plugin.

**Comment by phoward38** [comment]
@krankkkk I appreciate the workaround, but unfortunately clearing out my local image cache simply to install an extension isn't an option for me at the moment (we're setting up CI/CD to build our images with external services, but at the moment I rely on that cache for a number of long running builds).

Ideally, the code you pointed out where the error occurs would account for older images without tags if there is a newer version with any sort of tag (manual or `latest`).

@prakhar1989 Any thoughts on this? I've only glanced at the chunk of code that @krankkkk pointed out & it seems like a fairly minor fix, but I'm curious if you ran into any issues regarding this while creating the extension.

**Comment by flcdrg** [comment]
I can confirm that removing an image that was untagged (it had been superceded by a newer image) worked.

**Comment by jrobertson-insite** [comment]
Clearing the cache is not a valid fix/workaround. Hopefully this is fixed, I'd like to be able to use the dive-in extension.

**Comment by murlakatam** [comment]
For me it was clearing all untagged images
```bash
docker images -f dangling=true
```
```bash
docker images prune
```

And then pulling 
```bash
docker pull prakhar1989/dive-in
docker pull prakhar1989/dive
```

**Comment by phoward38** [comment]
@prakhar1989 Thanks for merging #7. An update here when it's been updated on the Docker Desktop Extension Marketplace would be great. Thanks!

**Comment by prakhar1989** [comment]
Updated docker hub: https://hub.docker.com/layers/prakhar1989/dive-in/0.0.8/images/sha256-0adcd44cc1cfcd4a6bdd85f0da02c69aa1603f4a85ce8d8f255e23d38cce8e25?context=explore

**Comment by phoward38** [comment]
@prakhar1989 Thanks, but unfortunately the newest version still throws the same error message
