### ISSUE TITLE
Stuck on Analyzing

### ISSUE THREAD

**Issue by TheRealFlyingCoder** [prakhar1989/dive-in#9]
Simple one, after fresh install, hitting analyze on a 16-bullseye-slim image, it just gets stuck analyzing

![image](https://user-images.githubusercontent.com/58131578/221067461-50156e22-87f1-4128-9ee3-3e3c529d0c45.png)

If I navigate away and come back it's back to the regular "Analyze" button

Windows 11
Docker Desktop v4.16.3 (96739)
Image - node:16-bullseye-slim

**Comment by mathiash98** [comment]
Same for me on MacOS M1
Using ContainerD for pulling and storing images
Docker version 4.17.0

**Comment by TheRealFlyingCoder** [comment]
The new Docker Scout early access for docker desktop makes this mostly irrelevant anyways i'm just gonna close this issue... 4 months without a response doesn't give much hope either haha
